[workspace]
members = [
    "crates/tidyup-core",
    "crates/tidyup-platform",
    "crates/tidyup-storage",
    "crates/tidyup-cli",
    "crates/tidyup-testkit",
]
resolver = "2"

[workspace.package]
license = "MIT"
repository = "https://github.com/NiketKakkar03/tidyup"
readme = "README.md"
keywords = ["files", "organization", "cli", "productivity"]
categories = ["command-line-utilities", "filesystem"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
